name: Expo CI/CD

#on:
 # push:
 #   branches:
  #    - develop
  #    - main
 # pull_request:
 #   branches:
 #     - develop
 #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Log in to Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Build on EAS
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            eas build --platform all --profile development --non-interactive
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            eas build --platform all --profile production --non-interactive
          fi
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  submit:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Submit to stores
        run: eas submit --platform all --latest --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
